version: 0.2


phases:
  install:
    runtime-versions:
    java: corretto8
    docker: 18
  pre_build:
   commands:
    - echo "Pre_build"
    - echo "Logging in to Amazon ECR"
#   - docker login --username sahaj01 --password 123456789
    - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
   commands:
    - echo "Build"
    - echo "Entered build phase"
    - echo "Building Java application"
    - cd Authorization-Microservice
    - mvn clean package
    - docker build -t pod-4-ij38:latest .
    - docker tag pod-4-ij38:latest 346916399611.dkr.ecr.us-east-1.amazonaws.com/pod-4-ij38


  post_build:
  commands:
    - echo "Post_build"
    - docker push 346916399611.dkr.ecr.us-east-1.amazonaws.com/pod-4-ij38:latest
    - printf '[{"name":"auth-container","imageUri":"%s"}]' 346916399611.dkr.ecr.us-east-1.amazonaws.com/pod-4-ij38:latest > taskdefinition.json
    - cat taskdefinition.json


artifacts:
 files:
 - book-service/taskdefinition.json