version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd processPensionMicroservice
   - mvn compile
   - mvn package
   - docker build -t pension/process .
   - docker tag pension/process 885843804602.dkr.ecr.us-east-1.amazonaws.com/process-pension:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/process-pension:latest
   - printf '[{"name":"process-pension-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/process-pension:latest > taskdefinition.json
artifacts:
 files:
  - processPensionMicroservice/taskdefinition.json