version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd pensionerDetailsMicroservice
   - mvn compile
   - mvn package
   - docker build -t pension/details .
   - docker tag pension/details 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-detail:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-detail:latest
   - printf '[{"name":"pension-detail-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-detail:latest > taskdefinition.json
artifacts:
 files:
  - pensionerDetailsMicroservice/taskdefinition.json
